language: ruby
rvm:
  - 2.0.0-p598

addons:
    postgresql: "9.3"

before_script:
  - "cp config/database.yml.postgresql_sample config/database.yml"
  - psql -c "create role kalibro_configurations with createdb login password 'kalibro_configurations'" -U postgres
  - "bundle exec rake db:setup db:migrate RAILS_ENV=test"
  - "bundle exec rake tmp:create"
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - export CODECLIMATE_REPO_TOKEN=6bf95f17eb6f76312a655acafc20c446a81f601c2f9a2c5d3771c95712da11d4

script:
  - bundle exec rake spec
  - bundle exec rake cucumber

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
